# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "blog-theme"
license = "MIT"
licenselink = "https://github.com/loongjuanfeng/blog-theme/blob/main/LICENSE"
description = "A fast, minimalist Hugo blog theme forked from no-style-please with modern Hugo APIs and CJK typography."
homepage = "https://github.com/loongjuanfeng/blog-theme"
tags = ["blog", "minimalist", "cjk"]
features = ["CJK typography"]
min_version = "0.158.0"

[author]
  name = "loongjuanfeng"
  homepage = "https://github.com/loongjuanfeng"

# If porting an existing theme
[original]
  name = "hugo-theme-nostyleplease"
  homepage = "https://github.com/Masellum/hugo-theme-nostyleplease"
  repo = "https://github.com/Masellum/hugo-theme-nostyleplease"
